export const themes = [
  { name: "lofi", icon: "📻", label: "Lofi" },
  { name: "light", icon: "☀️", label: "Light" },
  { name: "dark", icon: "🌙", label: "Dark" },
  { name: "cupcake", icon: "🧁", label: "Cupcake" },
  { name: "bumblebee", icon: "🐝", label: "Bumblebee" },
  { name: "emerald", icon: "💎", label: "Emerald" },
  { name: "corporate", icon: "🏢", label: "Corporate" },
  { name: "synthwave", icon: "🌈", label: "Synthwave" },
  { name: "retro", icon: "📺", label: "Retro" },
  { name: "cyberpunk", icon: "🤖", label: "Cyberpunk" },
  { name: "valentine", icon: "💝", label: "Valentine" },
  { name: "halloween", icon: "🎃", label: "Halloween" },
  { name: "garden", icon: "🌼", label: "Garden" },
  { name: "forest", icon: "🌲", label: "Forest" },
  { name: "aqua", icon: "🌊", label: "Aqua" },

  { name: "pastel", icon: "🌸", label: "Pastel" },
  { name: "fantasy", icon: "🧚‍♀️", label: "Fantasy" },
  { name: "wireframe", icon: "📐", label: "Wireframe" },
  { name: "black", icon: "⚫️", label: "Black" },
  { name: "luxury", icon: "💎", label: "Luxury" },
  { name: "dracula", icon: "🧛‍♂️", label: "Dracula" },
];
