export const themes = [
  { name: "lofi", icon: "📻", label: "Lofi", category: "Light" },
  { name: "light", icon: "☀️", label: "Light", category: "Light" },
  { name: "dark", icon: "🌙", label: "Dark", category: "Dark" },
  { name: "cupcake", icon: "🧁", label: "Cupcake", category: "Light" },
  { name: "bumblebee", icon: "🐝", label: "Bumblebee", category: "Light" },
  { name: "emerald", icon: "💎", label: "Emerald", category: "Light" },
  { name: "corporate", icon: "🏢", label: "Corporate", category: "Light" },
  { name: "synthwave", icon: "🌈", label: "Synthwave", category: "Light" },
  { name: "retro", icon: "📺", label: "Retro", category: "Light" },
  { name: "cyberpunk", icon: "🤖", label: "Cyberpunk", category: "Light" },
  { name: "valentine", icon: "💝", label: "Valentine", category: "Light" },
  { name: "halloween", icon: "🎃", label: "Halloween", category: "Dark" },
  { name: "garden", icon: "🌼", label: "Garden", category: "Light" },
  { name: "forest", icon: "🌲", label: "Forest", category: "Light" },
  { name: "aqua", icon: "🌊", label: "Aqua", category: "Light" },

  { name: "pastel", icon: "🌸", label: "Pastel", category: "Light" },
  { name: "fantasy", icon: "🧚‍♀️", label: "Fantasy", category: "Light" },
  { name: "wireframe", icon: "📐", label: "Wireframe", category: "Light" },
  { name: "black", icon: "⚫️", label: "Black", category: "Dark" },
  { name: "luxury", icon: "💎", label: "Luxury", category: "Dark" },
  { name: "dracula", icon: "🧛‍♂️", label: "Dracula", category: "Dark" },
];
